### ISSUE TITLE
Please update to 1.20.4

### ISSUE THREAD

**Issue by ItzSkyReed** [MaheEvil/SomeOrdinaryTweaks#12]

**Comment by AdelinaM17n** [comment]
The only feature that needs updating is the Skip Server Resource Packs thing and, honestly I am just too lazy right now.
Maybe next week

**Comment by Jackuhlf** [comment]
update?

**Comment by Jackuhlf** [comment]
please

**Comment by AdelinaM17n** [comment]
I will update to 1.20.4 and the upcoming .5 in the next month when I get holidays

**Comment by srnyx** [comment]
1.20.6 is the latest release now and 1.21 is right around the corner, any updates on this?

**Comment by ItzSkyReed** [comment]
Sadyl, but This mod os dead. It is better to forger about it, I think
