### ISSUE TITLE
Quilt Compat

### ISSUE THREAD

**Issue by DragonEggBedrockBreaking** [MaheEvil/SomeOrdinaryTweaks#4]
On Quilt, there is a way to entrypoint without QSL (noticed in the README that this is a potential issue for you). You need to use a Mixin that injects your code into the same place that an entrypoint would.

Mixin into `net.minecraft.server.Bootstrap.class`, then use the following injector, and place the code in the method:

```
@Inject(
    method = "bootStrap",
    at = @At(
        value = "INVOKE",
        target = "Lnet/minecraft/core/Registry;freezeBuiltins()V"
    )
)
private static void onInitialize(CallbackInfo ci) throws IOException {
}
```

**Comment by AdelinaM17n** [comment]
Yes I am well-aware I could do that, and I have considered it.
But meh as of now fabric compact in quilt works well enough I don't need to worry about that for now.

My interest for modding has decreased recently. and I mostly just intend to update my mods and develop for my own personal needs. So with quilt's plans to introduce things like their own config API I am not sure if I would have much energy/interest to migrate this mod another platform. 

If anyone want to maintain a full native quilt fork of this mod they can go right ahead.

**Comment by AdelinaM17n** [comment]
I have decided to keep updating the fabric version while making sure to not break quilt compat, instead of a native port
