### ISSUE TITLE
Make ModMenu Dependency Optional in mod.json

### ISSUE THREAD

**Issue by sisby-folk** [MaheEvil/SomeOrdinaryTweaks#5]
As above! mod loads just fine without modmenu - I personally use [ModSettings](https://modrinth.com/mod/mod-settings), but users could just poke the config files manually too.

**Comment by sisby-folk** [comment]
Here's an edited jar for anyone encountering this issue: [some-ordinary-tweaks-1.1.0.jar.zip](https://github.com/MaheEvil/SomeOrdinaryTweaks/files/9178875/some-ordinary-tweaks-1.1.0.jar.zip)

**Comment by AdelinaM17n** [comment]
Currently the reason mod-menu listed as required is to let more inexperienced users know that they need it to configure the mod, and its fair to assume those type of users would prefer not to find and manually configure the config file.

People using things ModSettings or would want manually poke at the config file I would assume are a niche, and in the latter case possibly more than capable of editing the json file themselves.

I can however consider releasing a separate file on modrinth that doesn't have modmenu listed as a required dependency.

**Comment by sisby-folk** [comment]
I'm a modpack dev, and so where possible I'd prefer to avoid bundling and
redistributing jars, because it inflates repo size. If it's at all possible
to have the json reflect the implementation more closely, that would be
helpful.

**Comment by AdelinaM17n** [comment]
After asking the opinion of another person, done - https://github.com/MaheEvil/SomeOrdinaryTweaks/commit/5ed8688888727305bc0928095c422edab4c66f43 

I'll consider adding some warning ingame instead (I do believe that is necessary as most of the mod's features are disabled by default)

Modrinth and CF will have the fixed version later today

**Comment by sisby-folk** [comment]
Thanks!
