### ISSUE TITLE
`No Double Slab Placement` prevents interacting with blocks even though not sneaking

### ISSUE THREAD

**Issue by TheGoldenThought** [MaheEvil/SomeOrdinaryTweaks#7]
When using `No Double Slab Placement` and looking at an interactable block for example a trapdoor or furnace, while not sneaking you are unable to open/use said block whilst holding slabs.

**Comment by AdelinaM17n** [comment]
Fixed in 064baf7 and backported to 1.19.3 in ba9ddb0
Modrinth and CF also updated
