### ISSUE TITLE
skip pack download not working with replay mod

### ISSUE THREAD

**Issue by itsMarkiS** [MaheEvil/SomeOrdinaryTweaks#8]
> download replay mod
> download someordinarytweaks
> enable the option of disabling server resourcepack download
> join a server that cointains a resource pack
> it will still download the server pack

**Comment by AdelinaM17n** [comment]
I'll take a look into it

**Comment by AdelinaM17n** [comment]
Should be fixed in the versions 1.19.4-1.6.5 and 1.19.3-.1.6.5-compatfix releases
1.19.4 fix commit - 5580f9d
1.19.3 fix commit - ea93c12

I have tested it myself and it should work, but please also test it yourself and close the issue if it is fixed

**Comment by itsMarkiS** [comment]
> Should be fixed in the versions 1.19.4-1.6.5 and 1.19.3-.1.6.5-compatfix releases 1.19.4 fix commit - [5580f9d](https://github.com/MaheEvil/SomeOrdinaryTweaks/commit/5580f9d2eeb1d56a49b046024051f99eff8d6ed2) 1.19.3 fix commit - [ea93c12](https://github.com/MaheEvil/SomeOrdinaryTweaks/commit/ea93c125e042c425f72f0f8efb6b4207a4490d84)
> 
> I have tested it myself and it should work, but please also test it yourself and close the issue if it is fixed

yes it does workss thxx, but could you make for 1.19.2 as well??? i tested in 1.19.3, but at the moment i still play in 1.19.2 cause of other mods that i use, thx

**Comment by AdelinaM17n** [comment]
> yes it does workss thxx, but could you make for 1.19.2 as well??? i tested in 1.19.3, but at the moment i still play in 1.19.2 cause of other mods that i use, thx

Right, alright I'll take backport it to 1.19.2
Mojang's new release schedule sure as hell made this a bit of a pain lol

**Comment by AdelinaM17n** [comment]
1.19.2 should also be updated (`fabric-1.19.2-backport-1.6.5` release on modrinth and CF), if there is any issue let me know

**Comment by itsMarkiS** [comment]
Working Perfectly ♥ tysmm
